### ISSUE TITLE
What license is this package distributed under?

### ISSUE THREAD

**Issue by izackp** [status-im/questionable#8]
There's no license file in the source code or any copyright notice of any kind. It would be nice to have some clarity here. 

Thanks for your time

**Comment by Menduist** [comment]
It's MIT, as can be seen in the nimble file
A license file will be added

**Comment by arnetheduck** [comment]
we should be using `MIT+Apache` for all our code cc @markspanbroek

**Comment by markspanbroek** [comment]
Thanks for pointing this out @izackp. I added a license file to clarify that we're releasing under the MIT or Apache-2.0 license.
